name: Lint HDL
on:
  push:
  pull_request:

permissions:
  contents: read

# Avoid multiple tests running on the same reference
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verible-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
      - name: Install make
        run: |
          sudo apt-get update
          sudo apt-get -y install make
      - uses: chipsalliance/verible-actions-common/install-verible@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run verible-verilog-lint
        run: make verible-lint 
  verilator-lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Clone yosys repo for simulation sources
        uses: actions/checkout@v4
        with:
          repository: YosysHQ/yosys
          path: ./yosys
          ref: main
          sparse-checkout: techlibs/xilinx/cells_sim.v
      - name: Copy cells_sim.v to /usr/share/yosys/xilinx/
        run: |
          sudo mkdir -p /usr/share/yosys/xilinx
          sudo cp ./yosys/techlibs/xilinx/cells_sim.v /usr/share/yosys/xilinx/
      - name: Clone verilator repo for verilator-docker
        uses: actions/checkout@v4
        with:
          repository: verilator/verilator
          path: ./verilator
          ref: master
          sparse-checkout: ci/docker/run/verilator-docker
      - name: Install make
        run: |
          sudo apt-get update
          sudo apt-get -y install make
      - uses: actions/checkout@v4
        with:
          path: ./analog-in-fw
      - name: Run verilator lint
        shell: bash
        working-directory: ./analog-in-fw
        run: |
          set -eo pipefail
          # Remove -ti option from verilator-docker
          sed -i 's|-ti||' "$GITHUB_WORKSPACE/verilator/ci/docker/run/verilator-docker"
          sudo touch /usr/bin/verilator
          sudo chmod +x /usr/bin/verilator
          echo '#!/usr/bin/env bash' | sudo tee /usr/bin/verilator
          echo "$GITHUB_WORKSPACE"'/verilator/ci/docker/run/verilator-docker "latest" "$@"'\
            | sudo tee /usr/bin/verilator
          make verilator-lint

