name: Lint HDL
on:
  push:
  pull_request:

permissions:
  contents: read

# Avoid multiple tests running on the same reference
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verible-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: 3j14/verible-actions-common/install-verible@optional-github-token
      - name: Run verible-verilog-lint on 'library'
        run: |
          files=$(find library \( -path library/red-pitaya-notes -o -path library/analog_devices_hdl \) -prune -false -o -name \*.v -o -name \*.sv)
          echo "Files:"
          echo $files
          verible-verilog-lint $files

  verilator-lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Clone yosys repo for simulation sources
        uses: actions/checkout@v4
        with:
          repository: YosysHQ/yosys
          path: ./yosys
          ref: main
          sparse-checkout: techlibs/xilinx/cells_sim.v

      - name: Copy cells_sim.v to /usr/share/yosys/xilinx/
        run: |
          sudo mkdir -p /usr/share/yosys/xilinx
          sudo cp ./yosys/techlibs/xilinx/cells_sim.v /usr/share/yosys/xilinx/

      - name: Install verilator
        run: |
          sudo apt-get update
          sudo apt-get -y install verilator

      - name: Run lint
        run: |
          files=$(find library \( -path library/red-pitaya-notes -o -path library/analog_devices_hdl \) -prune -false -o -name \*.v -o -name \*.sv)
          echo "Files:"
          echo $files
          verilator config.vlt \
          $files \
          /usr/share/yosys/xilinx/cells_sim.v \
          --lint-only \
          -y library/spi \
          --timing

